[project]
name = "youngernns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.7.5",
    "networkx>=3.1",
    "onnx-graphsurgeon>=0.5.2",
    "onnx2tf>=1.26.2",
    "onnx>=1.17.0",
    "onnxsim>=0.4.36",
    "sng4onnx>=1.0.4",
    "tensorflow>=2.17.0",
    "tf-keras>=2.17.0",
    "tf2onnx>=1.16.1",
    "toml>=0.10.2",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "tqdm",
]

[project.scripts]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
